---
title: "statistics_learning"
author: "David"
date: "2024-11-21"
output: github_document
---

```{r}
library(tidyverse)
library(glmnet)

set.seed(11)
```

try lasso

```{r}
bwt_df =
  read_csv("./data/birthweight.csv") |>
  janitor::clean_names() |>
  mutate(
    babysex =
      case_match(babysex,
                 1 ~ "male",
                 2 ~ "female"),
    babysex = fct_infreq(babysex),
    frace =
      case_match(frace,
                 1 ~ "white",
                 2 ~ "black",
                 3 ~ "asian",
                 4 ~ "puerto rican",
                 8 ~ "other"),
    frace = fct_infreq(frace),
    mrace =
      case_match(mrace,
                 1 ~ "white",
                 2 ~ "black",
                 3 ~ "asian",
                 4 ~ "puerto rican",
                 8 ~ "other"),
    mrace = fct_infreq(mrace),
  ) |>
  sample_n(200)

```

use glmnet
```{r}
x = model.matrix(bwt ~ ., data = bwt_df)[, -1]
y = bwt_df |> pull(bwt)
```


```{r}
lambda = 10^seq(-2, 2.75, by = 0.1)

lasso_fit =
  glmnet(x = x, y = y, lambda = lambda)

lasso_cv =
  cv.glmnet(x = x, y = y, lambda = lambda)

lambda_opt = lasso_cv[["lambda.min"]]
```

usual lasso plot

```{r}
lasso_fit |>
  broom::tidy() |>
  filter(term != "(Intercept)") |>
  select(term, lambda, estimate) |>
  complete(term, lambda, fill = list(estimate = 0)) |>
  ggplot(aes(x = lambda, y = estimate, group = term, color = term)) +
  geom_vline(xintercept = lambda_opt, color = "red") +
  geom_line()

```

```{r}
lasso_cv |>
  broom::tidy() |>
  ggplot(aes(x = log(estimate, 10), y = estimate)) +
  geom_point()

```


# cluster pokemons

```{r}
pokemon_df = 
  read_csv("data/pokemon.csv") |> 
  janitor::clean_names() |> 
  select(hp, speed)

pokemon_df |>
  ggplot(aes(x = hp, y = speed)) +
  geom_point()

```

k-means

```{r}
kmeans_fit =
  kmeans(x = pokemon_df, centers = 4)


pokemon_df =
  broom::augment(kmeans_fit, pokemon_df)

pokemon_df |>
  ggplot(aes(x = hp, y = speed, color = .cluster)) +
  geom_point()
```

